require('core-js');
require('reflect-metadata');
import 'rxjs/add/operator/do';
import 'rxjs/add/observable/empty';
import 'rxjs/add/operator/filter';
import 'rxjs/add/operator/take';
import 'rxjs/add/operator/mergeMap';
import 'rxjs/add/operator/delay';
import 'rxjs/add/observable/timer';
import 'rxjs/add/operator/toArray';
import 'rxjs/add/operator/select';
import '@ngrx/core/add/operator/select';